---
- name: creating ec2 instance
    ec2:
      key_name: "{{ keypair }}"
      instance_type: t2.micro
      image_id: "{{ image_id }}"
      wait: yes
      region: "{{ region }}"
      group_id: "{{ group_id }}"
      count: 1
      vpc_subnet_id: "{{ subnet_id }}"
      assign_public_ip: yes
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
